### ISSUE TITLE
接口错误

### ISSUE THREAD

**Issue by Dlian-Zero** [zhuweitung/banana-helper#2]
**错误描述**

接口错误

**使用版本**

> v0.2.11

**使用环境**

> GITHUB ACTIONS

**日志输出**

> > ------结束给Acer new个对象------

-----随机暂停2875ms-----

------每日签到任务开始------

每日签到成功：签到已成功，领取3蕉

------每日签到任务结束------

-----随机暂停2465ms-----

------投蕉任务开始------

自定义投蕉为：30根

请求视频投蕉接口出错，请稍后重试。错误请求信息：{"result":170004,"error_msg":"香蕉数不足","host-name":"hb2-acfun-kce-node66.aliyun"}

给视频：【独家X潇湘】我是大哥大OP~ 男人的勋章~ 投蕉失败

------投蕉任务结束------

-----随机暂停2078ms-----

------发送弹幕任务开始------

请求视频发送弹幕接口出错，请稍后重试。错误请求信息：{"result":128006,"error_msg":"","host-name":"hb2-acfun-kce-node77.aliyun"}

------发送弹幕任务结束------

-----随机暂停302ms-----

------点赞任务开始------

给视频：❀今天是古风邻家大姐姐❀ 点了个赞 ，收到点赞后楼妍LY_当场来了个后空翻~

------点赞任务结束------

-----随机暂停1823ms-----

------分享任务开始------

请求视频分享接口出错，请稍后重试。错误请求信息：{"result":105001,"error_msg":""}

------分享任务结束------

今日任务已全部执行完毕

您已经陪伴AC娘1441个日夜！以后也请多多关照~

AC在，爱一直在！

**Comment by zhuweitung** [comment]
> 请求视频发送弹幕接口出错，请稍后重试。错误请求信息：{"result":128006,"error_msg":"","host-name":"hb2-acfun-kce-node77.aliyun"}

其实弹幕发送已经成功了，不知道为什么A站的成功返回码变更了
